name: 📄Build and Publish Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Generate_Docs:
    name: Generate Documentation
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Install dependencies
        run: dotnet restore

      - name: Build Site
        working-directory: docfx_project
        run: docfx docfx.json
        continue-on-error: false

#      - name: Deploy Documentation
#        uses: JamesIves/github-pages-deploy-action@v4.3.3
#        with:
#          repository-name: DocFXSampleDocumentation
#          branch: master # The branch the action should deploy to.
#          folder: docs # The folder the action should deploy.
#          token: ${{ secrets.REPO_ACCESS }}
