name: 📄Build and Publish Documentation

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Generate_Docs:
    name: Generate Documentation
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Install dependencies
        run: dotnet restore

      - name: Build Site
        working-directory: docfx_project
        run: docfx .\docfx.json
        continue-on-error: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: KinsonDigital/DocFXSampleDocumentation
          publish_branch: master
          publish_dir: ./docfx_project/_site
          destination_dir: docs
          user_name: 'Calvin Wilkinson[DocFXSample Workflow]'
          user_email: 'kinsondigital@gmail.com'
          personal_token: ${{ secrets.REPO_ACCESS }}
          